version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 16
    commands:
      - echo Installing dependencies...
      - npm install -g @angular/cli
      - npm install
  build:
    commands:
      - echo Building the Angular app...
      - ng build

artifacts:
  files:
    - '**/*'
  base-directory: dist/frontend  # <-- Replace with your actual Angular app output folder name
